### ISSUE TITLE
Integração com pedidos

### ISSUE THREAD

**Issue by leoseefeld** [orangebr/pigz-gestao-desktop#6]
- Listagem de pedidos com filtros
- Alterar status de pedido
- Cancelar pedido

**Comment by leoseefeld** [comment]
@hugolima03 informar a situação desta demanda e se temos alguma pendências no backend para fecharmos.

**Comment by hugolima03** [comment]
Listagem de pedidos com filtros - pendente
Alterar status de pedido - concluído
Cancelar pedido - concluido
