### ISSUE TITLE
Integração com produtos

### ISSUE THREAD

**Issue by leoseefeld** [orangebr/pigz-gestao-desktop#7]
- [x]  Listagem de produtos
- [x]  Alterar o status do produto
- [x]  Edição básica de produto

**Comment by leoseefeld** [comment]
@hugolima03 listar aqui o que ainda está pendente nesta demanda e se precisa de algo a mais do backend para finalizarmos.

**Comment by hugolima03** [comment]
Listagem de produtos - concluído
Alterar o status do produto - pendente
Edição básica de produto - pendente

sem demandas para o backend.
